export { MessageService } from './api/message.service'
export { HistoryMessageType, HistoryTypeMessage } from './api/enums'
export { MessageBubble } from './ui/MessageBubble'
export { useMessageStore } from './model/useMessageStore'
export { BubblePosition, MessageDirection, MessageStatus } from './model/enums'
export type { Message } from './model/types'
export type { HistoryMessage } from './api/types'
